description: New Hampshire provides this base exemption based on filing status.
metadata:
  unit: currency-USD
  period: year
  breakdown:
  - filing_status
  label: New Hampshire base exemption amount
  reference: 
    - title: TECHNICAL INFORMATION RELEASE TIR 2025-001 I&D Tax Repealed Effective January 1, 2025
      href: https://www.revenue.nh.gov/sites/g/files/ehbemt736/files/documents/2025-001-technical-information-release-repeal.pdf
    - title: TITLE V - TAXATION - CHAPTER 77 - TAXATION OF INCOMES - Section 77:5
      href: https://www.gencourt.state.nh.us/rsa/html/V/77/77-5.htm
    - title: 2024 New Hampshire DP-10 Form Instructions
      href: https://www.revenue.nh.gov/sites/g/files/ehbemt736/files/documents/dp-10-instructions-2024.pdf#page=6
    - title: 2023 DP-10 Interest and Dividends Tax Return Instructions
      href: https://www.revenue.nh.gov/forms/2024/documents/dp-10-instructions-2023.pdf#page=6
    - title: 2022 DP-10 Interest and Dividends Tax Return Instructions
      href: https://www.revenue.nh.gov/forms/2023/documents/dp-10-instructions-2022.pdf#page=4
    - title: 2021 New Hampshire DP-10 Form
      href: https://www.revenue.nh.gov/forms/2022/documents/dp-10-2021-print.pdf#page=3
    - title: 2020 New Hampshire DP-10 Form (Line 6 - Base Exemptions)
      href: https://taxsim.nber.org/historical_state_tax_forms/NH/2020/dp-10-2020-print.pdf#page=3
    - title: 2008 New Hampshire DP-10 Form (Line 6 - Base Exemptions)
      href: https://taxsim.nber.org/historical_state_tax_forms/NH/2008/dp-10-2008.pdf#page=3
    - title: 2000 New Hampshire DP-10 Form (Line 6 - Base Exemptions)
      href: https://taxsim.nber.org/historical_state_tax_forms/NH/2000/dp-10-2000.pdf#page=3
    - title: 1995 New Hampshire DP-10 Form (Line 6 - Base Exemptions)
      href: https://taxsim.nber.org/historical_state_tax_forms/NH/1995/dp-10-1995.pdf#page=3
    - title: 1990 New Hampshire DP-10 Form (Line 6 - Base Exemptions)
      href: https://taxsim.nber.org/historical_state_tax_forms/NH/1990/dp-10-1990.pdf#page=2
SINGLE: 
  1977-01-01: 600
  1981-01-01: 1_200
  1995-01-01: 2_400
JOINT:
  1977-01-01: 1_200
  1981-01-01: 2_400
  1995-01-01: 4_800
SEPARATE:
  1977-01-01: 600
  1981-01-01: 1_200
  1995-01-01: 2_400
HEAD_OF_HOUSEHOLD: 
  1977-01-01: 600
  1981-01-01: 1_200
  1995-01-01: 2_400
SURVIVING_SPOUSE:
  1977-01-01: 600
  1981-01-01: 1_200
  1995-01-01: 2_400
